name: commit-check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          python -m pip install -e ".[dev]" --upgrade
      - name: commit check test
        run: |
          make commit-checks
